flying = read.table(file="https://raw.githubusercontent.com/OscarFHC/NRE538_2017Fall/master/Final/flying.csv",header=TRUE, sep=",")

college = read.table(file="https://raw.githubusercontent.com/OscarFHC/NRE538_2017Fall/master/Final/college.csv",header=TRUE, sep=",")

happy = read.table(file="https://raw.githubusercontent.com/OscarFHC/NRE538_2017Fall/master/Final/happy.csv",header=TRUE, sep=",")

cancer = read.table(file="https://raw.githubusercontent.com/OscarFHC/NRE538_2017Fall/master/Final/cancer.csv",header=TRUE, sep=",")
install.packages("ggplot2")
library(ggplot2)

#Question One
Gender = subset(flying, select=c(gender, unruly_child))
print(Gender)
Finalgender= na.omit(Gender)
print(Finalgender)
ctable= table(Finalgender$gender,Finalgender$unruly_child)
ctable
chisq.test(ctable)
Male = subset(Finalgender, gender== "Male")
head(Male)
Female= subset(Finalgender, gender == "Female")
head(Female)

#Question Two
Public = subset(college, type=="Public")
head(Public)
Private = subset(college, type=="Private nonprofit")
head(Private)
qqnorm(Public$tuition)
qqline(Public$tuition, col="Red")
shapiro.test(Public$tuition)
qqnorm(Private$tuition)
qqline(Private$tuition, col="red")
shapiro.test(Private$tuition)
qqnorm(college$tuition)
qqline(college$tuition, col="red")
shapiro.test(college$tuition)
var.test(Private[,"tuition"], Public[,"tuition"])
t.test(Private[,"tuition"], Public[,"tuition"], paired=FALSE)
t.test(Private[,"tuition"], Public[,"tuition"], alternative = "less")

#Question Three
qqnorm(happy$Hscore)
qqline(happy$Hscore, col='red')
shapiro.test(happy$Hscore)
install.packages("car")
library(car)
leveneTest(Hscore~Region,data=happy)
kruskal.test(Hscore~Region,data=happy)

install.packages("lmtest")
library(lmtest)
#Question Four
mod= lm(Corruption~Family+Life+Generosity, data=happy)
Happiness = subset(happy, select=c(Corruption, Family, Life, Generosity))
pairs(Happiness)
cor(Happiness)
plot(residuals(mod))
dwtest(mod, alternative=c("two.sided"))
bptest(mod)
qqnorm(residuals(mod))
qqline(residuals(mod), col="red")
shapiro.test(residuals(mod))
mod1 = lm(log(Corruption)~Family+Life+Generosity, data=happy)
dwtest(mod1, alternative=c("two.sided"))
bptest(mod1)
qqnorm(residuals(mod1))
qqline(residuals(mod1), col= 'red')
shapiro.test(residuals(mod1))
mod2= lm(sqrt(Corruption)~Family+Life+Generosity, data=happy)
dwtest(mod2, alternative=c("two.sided"))
bptest(mod2)
qqnorm(residuals(mod2))
qqline(residuals(mod2), col= 'red')
shapiro.test(residuals(mod2))
Corruption2= (happy$Corruption)^(1/9)
Mod3 = lm(Corruption2~Family+Life+Generosity, data=happy)
dwtest(Mod3, alternative=c("two.sided"))
bptest(Mod3)
qqnorm(residuals(Mod3))
qqline(residuals(Mod3), col= 'red')
shapiro.test(residuals(Mod3))
Mod3 = lm(Corruption2~Family+Life+Generosity, data=happy)
summary(Mod3)

#Question Five
install.packages("Lahman")
library(Lahman)
library(dplyr)
library(ggplot2)
mod4 = lm(Corruption2~ Generosity * Region, data= happy)
Ancova= subset(happy, select=c(Corruption, Region, Generosity))
pairs(Ancova)
plot(residuals(mod4))
dwtest(mod4, alternative=c("two.sided"))
bptest(mod4)
qqnorm(residuals(mod4))
qqline(residuals(mod4), col="red")
shapiro.test(residuals(mod4))
summary(mod4)

#Question Six
mod7=lm(malignant~texture_mean+smoothness_mean+area_mean, data=cancer)
mod6=glm(malignant~texture_mean+smoothness_mean+area_mean, data=cancer, family=binomial(link='logit'))
summary(mod6)
Tumor = subset(cancer, select=c(malignant, texture_mean, smoothness_mean, area_mean))
pairs(Tumor)
cor(Tumor)
plot(residuals(mod7))
dwtest(mod7, alternative=c("two.sided"))
bptest(mod7)
qqnorm(residuals(mod7))
qqline(residuals(mod7), col="red")
shapiro.test(residuals(mod7))
summary(mod6)
summary(mod6)
plot(mod6, which=1)
