flying=read.csv('/Users/katiepritchard/Downloads/flying.csv')
college=read.csv('/Users/katiepritchard/Downloads/college_final.csv')
happy=read.csv('/Users/katiepritchard/Downloads/happy.csv')
cancer=read.csv('/Users/katiepritchard/Downloads/cancer.csv')

##Question 1
library(MASS)
tbl=table(flying$gender, flying$unruly_child)
tbl
men=subset(flying, gender=="Male")
women=subset(flying, gender=="Female")
chisq.test(tbl)

##Question 2
boxplot(tuition~type, data=college, ylab="Effect Size", xlab="Type of College", main="College Tuition by College Type")
private=subset(college, type=="Private nonprofit")
public=subset(college, type=="Public")
hist(college$tuition)
shapiro.test(college$tuition)
hist(private$tuition, xlab="Tuition (dollars)")
shapiro.test(public$tuition)
hist(public$tuition, xlab="Tuition (dollars)")
var.test(private$tuition, public$tuition)
t.test(private$tuition, public$tuition, paired=FALSE, var.equal=FALSE)

##Question 3
boxplot(Hscore~Region, data=happy, xlab="Region", ylab="Effect Size", main="Regional Happiness Scores")
AM=subset(happy, Region=="AfricaMideast")
AC=subset(happy, Region=="AmericasCarribean")
AA=subset(happy, Region=="AsiaAustralia")
EU=subset(happy, Region=="Europe")
library(car)
shapiro.test(happy$Hscore)
leveneTest(Hscore~Region, data=happy)
aov=aov(Hscore~Region, data=happy)
summary(aov)

##Question 4
#Choosing my independent variables
library(dplyr)
library(lmtest)
library(car)
install.packages('faraway')
library(faraway)
lma=lm(Corruption~Generosity+Freedom+Life+Hrank+Hscore+Family, data=happy)
summary(lma)
#Freedom, Hscore, and Family appear to have a significant effect on Corruption
#To check for collinearity...
cor(happy[,c(4,6,8,9)], use="na.or.complete")
vif(lm(Corruption~Freedom+Hscore+Family, data=happy))

#Model checking
hist(happy$Corruption, xlab="Corruption", main="Histogram of Corruption")
shapiro.test(happy$Corruption)
mod=lm(Corruption~Freedom+Family+Hscore, data=happy)
summary(mod)
qqnorm(residuals(mod))
qqline(residuals(mod), col="red")
#Log transformation
happy$log_Y=log(happy$Corruption)
shapiro.test(happy$log_Y)
hist(happy$log_Y, xlab="Log(Corruption)", main="Histogram of Log(Corruption)")
mod_log=lm(happy$log_Y~happy$Freedom+happy$Family+happy$Hscore)
summary(mod_log)
plot(residuals(mod_log))
dwtest(mod_log, alternative=c("two.sided"))
bptest(mod_log)
shapiro.test(residuals(mod_log))
qqnorm(residuals(mod_log), main="Log Transformed Y Q-Q Plot")
qqline(residuals(mod_log), col="red")
#Square root transformation
happy$sqrt_Y=sqrt(happy$Corruption)
shapiro.test(happy$sqrt_Y)
hist(happy$sqrt_Y, xlab="Square Root(Corruption)", main="Histogram of Square Root(Corruption)", ylim=c(0, 40))
mod_sqrt=lm(happy$sqrt_Y~happy$Freedom+happy$Family+happy$Hscore)
summary(mod_sqrt)
plot(residuals(mod_sqrt))
dwtest(mod_sqrt, alternative=c("two.sided"))
bptest(mod_sqrt)
shapiro.test(residuals(mod_sqrt))
qqnorm(residuals(mod_sqrt), main="Square Root Transformed Y Q-Q Plot")
qqline(residuals(mod_sqrt), col="red")
install.packages('gvlma')
library(gvlma)
gvlma(lm(Corruption~Generosity+Freedom+Life, data=happy))
#Cube root transformation
happy$cube_Y=(happy$Corruption)^(1/3)
shapiro.test(happy$cube_Y)
hist(happy$cube_Y, xlab="Cube Root(Corruption)", main="Histogram of Cube Root(Corruption)", ylim=c(0, 40))
mod_cube=lm(happy$cube_Y~happy$Freedom+happy$Family+happy$Hscore)
summary(mod_cube)
plot(residuals(mod_cube))
dwtest(mod_cube, alternative=c("two.sided"))
bptest(mod_cube)
shapiro.test(residuals(mod_cube))
qqnorm(residuals(mod_cube), main="Cube Root Transformed Y Q-Q Plot")
qqline(residuals(mod_cube), col="red")
cor(happy[,c("cube_Y", "Family", "Freedom", "Hscore")])

#Question 5
library(Lahman)
library(dplyr)
mod.ancova=lm(cube_Y~Freedom*Region, data=happy)
summary(mod.ancova)

#Question 6
mod.test=lm(malignant~area_mean+texture_mean+smoothness_mean, data=cancer)
par(mfrow=c(2,2))
plot(mod.test)
cor(cancer)
pairs(cancer)
modt=glm(malignant~texture_mean+area_mean+smoothness_mean, data=cancer, family=binomial(link="logit"))
summary(modt)

#Question 7
mod0=glm(malignant~1, data=cancer, family=binomial(link="logit"))
summary(mod0)
mod1=glm(malignant~radius_mean, data=cancer, family=binomial(link="logit"))
summary(mod1)
mod2=glm(malignant~radius_mean+texture_mean, data=cancer, family=binomial(link="logit"))
summary(mod2)
mod3=glm(malignant~radius_mean+texture_mean+area_mean, data=cancer, family=binomial(link="logit"))
summary(mod3)
anova(mod0,mod1,mod2,mod3, test="Chi")
AIC(mod0, mod1,mod2,mod3)
